user:
    resource: "@UserBundle/Resources/config/routing/routing.yml"
    prefix:   /admin

app:
    resource: "@AppBundle/Resources/config/routing/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
